### ISSUE TITLE
Support for Microsoft DependencyInjection

### ISSUE THREAD

**Issue by dshe** [Divergic/Divergic.Logging.Xunit#10]
Please provide support for **Microsoft.Extensions.DependencyInjection**:

`new ServiceCollection().AddLogging((builder) => builder.AddXUnit(OutputHelper, Formatter))`

```
public static class XUnitLoggerProviderExtensions
{
    public static void AddXUnit(this ILoggingBuilder builder, ITestOutputHelper output,
        Func<int, string, LogLevel, EventId, string, Exception, string> formatter = null)
    {
        var provider = new TestOutputLoggerProvider(output, formatter);
        builder.AddProvider(provider);
    }
}

```

**Comment by roryprimrose** [comment]
Can you please verify that this works as expected. The PR package is on MyGet at https://www.myget.org/feed/divergic/package/nuget/Divergic.Logging.Xunit/2.2.0-pullrequest0011-0004
