### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by riezebosch** [Divergic/Divergic.Logging.Xunit#15]
Don't understand the dependencies on `Ensure.That (>= 8.1.1)` and `Newtonsoft.Json (>= 12.0.1)`

**Comment by roryprimrose** [comment]
This does not appear to be either a question nor an issue with the code.

Have you searched the code base for where these packages are used?

**Comment by riezebosch** [comment]
Did check it out and learned a new library. Expected `Ensure.That` to be an assertion framework.
